import React from "react";

export default function MemoryTab({ activeSession }) {
  return (
    <div className="eval-panel-container">
      <div className="eval-run-card">
        <div style={{ fontWeight: 600, fontSize: "1.1rem", color: "var(--text-primary)", display: "flex", alignItems: "center", gap: "10px" }}>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--accent-green)" strokeWidth="2">
            <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
            <circle cx="12" cy="7" r="4"></circle>
          </svg>
          Extracted User Facts
        </div>
        <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)", lineHeight: "1.5" }}>
          Real-time personalization profile generated by background summarization.
        </p>
        <div className="fact-list" style={{ marginTop: "16px" }}>
          {activeSession && activeSession.user_facts.map((fact, idx) => (
            <div key={idx} className="fact-item">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                <polyline points="20 6 9 17 4 12"></polyline>
              </svg>
              {fact}
            </div>
          ))}
          {(!activeSession || activeSession.user_facts.length === 0) && (
            <div style={{ fontSize: "0.85rem", color: "rgba(255,255,255,0.3)", fontStyle: "italic", textAlign: "center", padding: "16px 0" }}>
              No user facts extracted yet. Share details about yourself to watch it learn.
            </div>
          )}
        </div>
      </div>

      <div className="eval-results-container">
        <div style={{ fontWeight: 600, fontSize: "1.05rem", color: "var(--text-primary)", marginBottom: "4px" }}>
          Conversational Window Context
        </div>
        <div style={{ fontSize: "0.85rem", color: "var(--accent-cyan)", marginBottom: "20px" }}>
          Sliding Turns (Active vs Pruned)
        </div>
        <div className="memory-history-viewer">
          {activeSession && activeSession.messages.filter(m => m.role !== "system").map((msg, idx) => {
            const isSystemDecoration = msg.content.includes("I am calling tool") || (msg.content.includes("Tool '") && msg.content.includes("returned output:"));
            if (isSystemDecoration) return null;

            return (
              <div key={idx} className={`memory-history-card ${msg.in_context ? "active" : "expired"}`}>
                <div className="memory-card-header">
                  <span style={{ color: msg.role === "user" ? "var(--accent-blue)" : "var(--accent-purple)", fontWeight: 800 }}>
                    {msg.role.toUpperCase()}
                  </span>
                  <span style={{ 
                    background: msg.in_context ? "rgba(0, 242, 96, 0.15)" : "rgba(255, 51, 102, 0.15)",
                    color: msg.in_context ? "var(--accent-green)" : "var(--accent-red)",
                    padding: "3px 10px", borderRadius: "12px", fontSize: "0.7rem", fontWeight: 700
                  }}>
                    {msg.in_context ? "ACTIVE" : "PRUNED"}
                  </span>
                </div>
                <div className="memory-card-text" style={{ marginTop: "10px", color: "var(--text-primary)" }}>{msg.content}</div>
              </div>
            );
          })}
          {(!activeSession || activeSession.messages.length === 0) && (
            <div style={{ fontSize: "0.85rem", color: "rgba(255,255,255,0.3)", fontStyle: "italic", textAlign: "center", padding: "24px 0" }}>
              Chat thread is empty. Send messages to see history context states.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
